account = "QC70969-DTNA_PROD"
user = "VMASHET"
role = "DEV_DATAENINEER_FR"
database = "DEV_DB"
schema = "VMASHET"
warehouse = "DEV_ADHOC_ANALYSIS_WH"
private_key_file = "C:/Users/VMASHET/snowflake_keys/VMASHET_snowflake.p8"
authenticator = "SNOWFLAKE_JWT"